# Find libAMBIX.

FIND_PATH(LIBAMBIX_INCLUDE_DIR ambix/ambix.h)

SET(LIBAMBIX_NAMES ${LIBAMBIX_NAMES} ambix libambix)
FIND_LIBRARY(LIBAMBIX_LIBRARY NAMES ${LIBAMBIX_NAMES} PATH)

IF(LIBAMBIX_INCLUDE_DIR AND LIBAMBIX_LIBRARY)
	SET(LIBAMBIX_FOUND TRUE)
ENDIF(LIBAMBIX_INCLUDE_DIR AND LIBAMBIX_LIBRARY)

IF(LIBAMBIX_FOUND)
	IF(NOT LibAmbix_FIND_QUIETLY)
		MESSAGE(STATUS "Found LibAmbix: ${LIBAMBIX_LIBRARY}")
	ENDIF (NOT LibAmbix_FIND_QUIETLY)
ELSE(LIBAMBIX_FOUND)
	IF(LibAmbix_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find ambix")
	ENDIF(LibAmbix_FIND_REQUIRED)
ENDIF (LIBAMBIX_FOUND)